import React from 'react';

const PrivacyPolicy = () => {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center">
      <div className="w-full bg-white px-8 py-8 md:px-40">
        <h1 className="mb-8 text-4xl font-bold md:text-[4rem]">QuikFixs Privacy Policy</h1>
        <div className="mb-8 h-1 w-full bg-black" />
        <div className="text-xl text-black">
          <p className="mb-8">QuikFixs is owned and operated by QUIKFIXS SERVICES INC.</p>
          <p className="mb-8">
            QuikFixs values your privacy and the protection of your personal data. This privacy policy describes what
            information we collect from you, how we collect it, how we use it, how we obtain your consent, how long we
            keep it in our databases and, if necessary, with whom we share it.
          </p>
          <p className="mb-8">
            By using the platform, you are accepting the practices described in this privacy policy. The use of the
            platform is also subject to our terms and conditions. In this privacy policy the words “platform” refer to
            the QuikFixs mobile application and the QuikFixs website together, &quot;we&quot;, &quot;us&quot;,
            &quot;our&quot;, and &quot;QuikFixs&quot;, refers to QuikFixs, and &quot;you&quot;, and &quot;user&quot;,
            refers to you, the QuikFixs user (Customers and Contractors).{' '}
          </p>
          <p className="mb-8">
            This privacy policy may change from time to time. Your continued use of the platform after we make changes
            is deemed to be acceptance of those changes, so please check the policy periodically for updates. This
            privacy policy has been developed and is maintained in compliance with all applicable state and federal
            privacy and data protection laws and regulations.
          </p>

          <h2 className="mb-8 text-4xl font-semibold">1. GENERAL INFORMATION</h2>
          <p className="mb-8">The personal data of the users that are collected and processed through the platform:</p>
          <ul className="mb-8 list-inside list-disc">
            <li>QuikFixs mobile application (Available on Google Play and App Store).</li>
            <li>QuikFixs website (https://www.quikfixs.com)</li>
          </ul>
          <p className="mb-8">The personal data of the users that are collected and processed through the platform:</p>
          <ul className="mb-8 list-inside list-disc">
            <li>QUIKFIXS SERVICES INC.</li>
            <li>Email: support@quikfixs.com</li>
          </ul>

          <h2 className="mb-8 text-4xl font-semibold">2. HOW WE OBTAIN YOUR CONSENT</h2>
          <p className="mb-8">
            By using QuikFixs, you give your informed consent for the collection, use, and processing of your personal
            information in accordance with this privacy policy. This consent is considered to be given voluntarily and
            expressly when you do any of the following:
          </p>
          <ul className="mb-8 list-inside list-disc">
            <li>Downloading and installing the QuikFixs application from Google Play or the App Store.</li>
            <li>Browsing the official QuikFixs website.</li>
            <li>Registering as a user on the platform, either as a Customer or a Contractor.</li>
            <li>Making, confirming, and paying for a service request through the application (Customers).</li>
            <li>Accepting and completing a service request assigned through the platform (Contractors).</li>
            <li>Providing a review or rating of a service received through the application (Customers).</li>
            <li>Making general use of the features offered by the QuikFixs platform.</li>
            <li>Communicating with QuikFixs through any of the available contact channels.</li>
          </ul>
          <p className="mb-8">
            In accordance with applicable privacy laws in the United States, including the general framework of the
            Federal Trade Commission (FTC) and other applicable state regulations, obtaining your consent through these
            actions constitutes a legitimate legal basis for processing your personal information. You have the right to
            revoke your consent at any time, which may affect your access to or use of certain features of the platform.
            By continuing to use QuikFixs&apos; services, you acknowledge that you have read and understood this Privacy
            Policy and expressly consent to the processing of your personal data in accordance with the terms described
            herein.
          </p>

          <h2 className="mb-8 text-4xl font-semibold">3. TYPES OF INFORMATION GATHERED</h2>
          <p className="mb-8">
            QuikFixs collects and processes various types of personal data provided or generated by users when
            interacting with the mobile application, website, or related services. The information may be collected
            directly when completing forms or using specific features, or automatically through tracking and analysis
            technologies. The types of data that QuikFixs may collect include, but are not limited to, the following:
          </p>
          <p className="mb-8 text-2xl">
            <strong>3.1. Personal data</strong>
          </p>
          <p className="mb-8">
            This includes information that you provide directly when registering or communicating with us, such as:
          </p>
          <ul className="mb-8 list-inside list-disc">
            <li>First and last name</li>
            <li>Email address</li>
            <li>Mobile phone number</li>
            <li>Physical address (if necessary for the provision of the service)</li>
            <li>Profile photo (when uploaded by the user)</li>
          </ul>

          <p className="mb-8 text-2xl">
            <strong>3.2. Registration and user profile data</strong>
          </p>
          <p className="mb-8">
            This includes information generated during the account creation and profile setup process within the
            platform, including:
          </p>
          <ul className="mb-8 list-inside list-disc">
            <li>Account type (Customer or Contractor)</li>
            <li>Password and login credentials</li>
            <li>Service preferences or specialties</li>
            <li>Availability and general location (for contractors)</li>
            <li>Identity verification or documentation status</li>
          </ul>

          <p className="mb-8 text-2xl">
            <strong>3.3. Payment and billing data</strong>
          </p>
          <p className="mb-8">
            This is data collected when making a service request or accepting payments through the application, and
            includes:
          </p>
          <ul className="mb-8 list-inside list-disc">
            <li>Payment method details (e.g., credit/debit card tokenized through the payment provider)</li>
            <li>Transaction and billing information</li>
            <li>Records of applicable payments, fees, and refunds</li>
          </ul>

          <p className="mb-8 text-2xl">
            <strong>3.4. Automatically collected data</strong>
          </p>
          <p className="mb-8">
            This includes information that is collected automatically through the use of the website and mobile
            application, such as:
          </p>
          <ul className="mb-8 list-inside list-disc">
            <li>Device identifiers, operating system, and application version</li>
            <li>IP address, time zone, and approximate geographic location</li>
            <li>Browsing history within the application or website</li>
            <li>Usage times, clicks, errors, and other technical data related to the operation of the platform</li>
          </ul>

          <p className="mb-8 text-2xl">
            <strong>3.5. Analytical data</strong>
          </p>
          <p className="mb-8">
            This is collected through analysis tools in order to improve performance and user experience, and includes:
          </p>
          <ul className="mb-8 list-inside list-disc">
            <li>General interactions with the application or website</li>
            <li>Behavior patterns and frequency of use</li>
            <li>Conversion, abandonment, or satisfaction metrics</li>
          </ul>

          <p className="mb-8 text-2xl">
            <strong>3.6. Contact and communications data</strong>
          </p>
          <p className="mb-8">
            This includes data provided when contacting QuikFixs, whether through forms, email, calls, or other enabled
            means, such as:
          </p>
          <ul className="mb-8 list-inside list-disc">
            <li>Content of messages and requests made</li>
            <li>Date, time, and means of communication</li>
            <li>Name and identifying information included in the query</li>
          </ul>

          <h2 className="mb-8 text-4xl font-semibold">4. HOW LONG WE KEEP YOUR DATA</h2>
          <p className="mb-8">
            Personal data provided by users through the platform will be retained for the time necessary to fulfill the
            legitimate purposes described in section 5 of this policy and/or until the user stops using the platform,
            closes the user account, uninstalls the app or requests the deletion of their data. In the case of reviews,
            they will remain visible on the platform. By posting a review on the platform the user grants an irrevocable
            license to display the review on the platform indefinitely. QuikFixs may retain personal data for a longer
            period provided that the user has given consent to such processing, as long as such consent is not
            withdrawn. In addition, QuikFixs may be obliged to retain personal data for a longer period if required to
            do so in order to comply with a legal obligation or by order of an authority. Once the retention period has
            expired, the personal data will be deleted. Therefore, the right of access, the right of deletion, the right
            of rectification and the right of data portability cannot be asserted after the retention period has
            expired.
          </p>

          <h2 className="mb-8 text-4xl font-semibold">5. PURPOSES OF DATA COLLECTION</h2>
          <p className="mb-8">
            QuikFixs collects and processes its users&apos; personal data for the purpose of providing its services in
            an effective, secure, and personalized manner. Each category of information collected serves legitimate and
            specific purposes directly related to the operation of the application and the user experience. The purposes
            for which the different types of data are used are detailed below:
          </p>
          <p className="mb-8 text-2xl">
            <strong>5.1. Personal data</strong>
          </p>
          <p className="mb-8">This data is necessary to:</p>
          <ul className="mb-8 list-inside list-disc">
            <li>Uniquely identify users of the platform.</li>
            <li>
              Establish direct communication between QuikFixs and the user, as well as between Customers and Contractors
              when relevant to the provision of the service.
            </li>
            <li>
              Send confirmations, reminders, and operational notifications related to the use of the platform or service
              requests.
            </li>
            <li>
              Manage user account security, prevent unauthorized access, and provide technical support or personalized
              assistance.
            </li>
          </ul>

          <p className="mb-8 text-2xl">
            <strong>5.2. Registration and user profile data</strong>
          </p>
          <p className="mb-8">Profile information is used to:</p>
          <ul className="mb-8 list-inside list-disc">
            <li>
              Configure the account and tailor the user experience according to their role (Customer or Contractor).
            </li>
            <li>Display the necessary information in the application to facilitate interaction between users.</li>
            <li>
              Automatically and efficiently assign the most suitable Contractors to Customer service requests, based on
              availability, location, specialty, and other relevant criteria.
            </li>
            <li>
              Facilitate compliance with internal eligibility requirements, identity validation or professional
              verification, where applicable.
            </li>
          </ul>

          <p className="mb-8 text-2xl">
            <strong>5.3. Payment and billing data</strong>
          </p>
          <p className="mb-8">This data is processed to:</p>
          <ul className="mb-8 list-inside list-disc">
            <li>Manage payments for services requested by Customers.</li>
            <li>Make the corresponding payments to Contractors after the service has been provided.</li>
            <li>Issue receipts, invoices, and maintain a transaction history for both types of users.</li>
            <li>Process refunds, adjustments, or disputes related to payments.</li>
          </ul>

          <p className="mb-8 text-2xl">
            <strong>5.4. Data collected automatically by the application and website</strong>
          </p>
          <p className="mb-8">This type of information allows QuikFixs to:</p>
          <ul className="mb-8 list-inside list-disc">
            <li>Ensure the proper functioning of the application and website.</li>
            <li>Detect technical errors, prevent fraudulent activities, and maintain the integrity of the platform.</li>
            <li>
              Adjust system performance to the characteristics of the user&apos;s device and technical environment.
            </li>
            <li>
              Determine the approximate location to suggest available services, improve the accuracy of assignments, and
              facilitate the logistics of service delivery.
            </li>
          </ul>

          <p className="mb-8 text-2xl">
            <strong>5.5. Analytical data</strong>
          </p>
          <p className="mb-8">Collected for the following purposes:</p>
          <ul className="mb-8 list-inside list-disc">
            <li>To understand usage patterns and behavior within the application and website.</li>
            <li>To improve the design, navigation, and functionality of the platform.</li>
            <li>
              To optimize internal processes, detect points of friction, and improve user retention and satisfaction.
            </li>
            <li>To measure the effectiveness of new features and promotional campaigns.</li>
          </ul>

          <p className="mb-8 text-2xl">
            <strong>5.6. Contact and communication data</strong>
          </p>
          <p className="mb-8">This information is processed to:</p>
          <ul className="mb-8 list-inside list-disc">
            <li>Respond effectively to queries, complaints, or requests for information.</li>
            <li>Follow up on previous interactions, resolve incidents, and provide personalized support.</li>
            <li>Maintain an internal record of communications established with users.</li>
          </ul>

          <h2 className="mb-8 text-4xl font-semibold">6. HOW WE SHARE INFORMATION</h2>
          <p className="mb-8">
            The personal information of our customers and users is an important and fundamental part of our platform.
            Under no circumstances will we sell or share information with third parties that has not been previously
            authorized by the user or owner of the personal data. We share user information only and exclusively as
            described below.
          </p>
          <p className="mb-8">
            Third-Party Service Providers. We use third-party services to perform certain functions on our platform.
            Some of these functions and services include: hosting the app in the app stores (App Store and Google Play),
            hosting the website, data storage services, processing payments (Stripe), sending emails, and performing
            tracking and analytics functions on the platform.
          </p>
          <p className="mb-8">
            These third-party services and tools may have access to personal information needed to perform their
            functions, but may not use that information for other purposes. Information shared with these third-party
            services will be treated and stored in accordance with their respective privacy policies and our privacy
            policy.
          </p>
          <p className="mb-8">
            Newsletter and email marketing: By providing us with your email address, you consent and agree that we may
            send you marketing content and newsletters, notifications and information related to our platform.
            Therefore, your email address may be shared with third party bulk email services for the sole and exclusive
            purpose of sending you relevant communications. If you wish to stop receiving communications from QuikFixs,
            you can unsubscribe at any time by using the &quot;unsubscribe&quot; option available in the same emails or
            by sending your request through our contact information.
          </p>
          <p className="mb-8">
            Data shared with other users: By registering on the platform and requesting services through QuikFixs,
            Customers expressly authorize their relevant personal data, such as name, service address, telephone number,
            and request details, to be shared with the assigned Contractors for the sole purpose of facilitating the
            performance of the requested service and fulfilling the legitimate purposes of the platform. This sharing of
            information is essential for Contractors to contact the Customer, learn about the details of the work to be
            performed, go to the agreed location, and provide efficient and personalized service. QuikFixs limits this
            transfer to only the information necessary for the performance of the specific activity and requires
            Contractors to use such information confidentially and in accordance with the platform&apos;s terms of use.
          </p>
          <p className="mb-8">
            Business Transfers. In the event that QuikFixs creates, merges with, or is acquired by another entity, your
            information will most likely be transferred. QuikFixs will email you or place a prominent notice on our
            platform before your information becomes subject to another privacy policy.
          </p>
          <p className="mb-8">
            Protection of QuikFixs and others. We release personal information when we believe release is appropriate to
            comply with the law, enforce or apply our Terms and conditions and other agreements, or protect the rights,
            property, or safety of QuikFixs, our users or others. This includes exchanging information with other
            companies and organizations for fraud protection and credit risk reduction.
          </p>
          <p className="mb-8">
            With Your Consent. Other than as set out above, you will receive notice when personally identifiable
            information about you might go to third parties, and you will have an opportunity to choose not to share the
            information.
          </p>
          <p className="mb-8">
            Anonymous Information. QuikFixs uses the anonymous browsing information collected automatically by our
            servers primarily to help us administer and improve the platform. We may also use aggregated anonymous
            information to provide information about the platform to potential business partners and other unaffiliated
            entities. This information is not personally identifiable.
          </p>

          <h2 className="mb-8 text-4xl font-semibold">7. PROTECTING YOUR INFORMATION</h2>
          <p className="mb-8">
            We grant access to your personal information only to those outside persons or services that have a
            legitimate need to know it and in accordance with our privacy policy. We adhere to industry-recognized
            security standards to protect your personal information, both during transmission and in storage. However,
            it is important to note that no method of transmission over the Internet or electronic storage is foolproof
            and 100% secure. Therefore, while we at QuikFixs strive to implement commercially viable data protection
            methods, we cannot ensure absolute security of your personal information. We undertake not to sell,
            distribute or transfer your personal data to unauthorized third parties, unless we have your explicit
            consent or are required by law to do so.
          </p>

          <h2 className="mb-8 text-4xl font-semibold">8. DATA BREACH NOTIFICATIONS</h2>
          <p className="mb-8">
            In the event of a security breach that compromises the confidentiality of our users&apos; personal data,
            QuikFixs undertakes to notify those affected in a timely manner. This notification will be made through the
            means of contact that have been provided by the user on our platform. We will take all reasonable measures
            to protect the information and remedy any situation that jeopardizes the security of your data.
          </p>

          <h2 className="mb-8 text-4xl font-semibold">9. INTERNATIONAL DATA TRANSFER</h2>
          <p className="mb-8">
            QuikFixs may transfer users&apos; personal data outside of the United States due to the use of hosting,
            storage and processing services provided by third parties that operate servers located in different
            countries. These transfers are necessary to ensure the continued operation of the platform and to provide an
            efficient user experience. Although QuikFixs is based in the United States, the technology infrastructure
            used may involve data being stored or processed in jurisdictions with data protection laws other than the
            United States.
          </p>
          <p className="mb-8">
            QuikFixs is committed to ensuring that all international transfers of personal data comply with applicable
            data protection regulations, including appropriate security measures to safeguard user information. This
            includes, but is not limited to, implementing standard contractual clauses, assessing the adequacy of data
            protection in the receiving country, and complying with applicable privacy standards on third party
            services.
          </p>
          <p className="mb-8">
            By using QuikFixs, users consent to the transfer, storage and processing of their data on servers located
            outside their country of residence, acknowledging that such transfers are necessary for the operation of the
            platform. QuikFixs undertakes to take all reasonable steps to protect the integrity and security of personal
            data during such international transfers.
          </p>

          <h2 className="mb-8 text-4xl font-semibold">10. RIGHTS</h2>
          <p className="mb-8">
            Users who provide information through our platform, as data subjects and data owners, have the right to
            access, rectify, download or delete their information, as well as to restrict and object to certain
            processing of their information. While some of these rights apply generally, others apply only in certain
            limited circumstances. We describe these rights below:
          </p>
          <ul className="mb-8 list-inside list-disc">
            <li>
              Access and portability: to access and know what information is stored in our servers, you can send us your
              request through our contact information.
            </li>
            <li>
              Rectify, Restrict, Limit and/or Delete: You can also rectify, restrict, limit or delete much of your
              information.
            </li>
            <li>
              Right to be informed: Users of our platform will be informed, upon request, about what data we collect,
              how it is used, how long it is retained and whether it is shared with third parties.
            </li>
            <li>
              Object: When we process your information based on our legitimate interests as explained above, or in the
              public interest, you may object to this processing in certain circumstances. In such cases, we will stop
              processing your information unless we have compelling legitimate reasons to continue processing it or
              where it is necessary for legal reasons.
            </li>
            <li>
              Revoke consent: Where you have previously given your consent, such as to allow us to process and store
              your personal information, you have the right to revoke your consent to the processing and storage of your
              information at any time. For example, you may withdraw your consent by updating your settings. In certain
              cases, we may continue to process your information after you have withdrawn your consent if we have a
              legal basis for doing so or if your withdrawal of consent was limited to certain processing activities.
            </li>
            <li>
              Complaint: If you wish to file a complaint about our use of your information (and without prejudice to any
              other rights you may have), you have the right to do so with your local supervisory authority. Users can
              exercise all these rights by contacting us through the contact information or the contact page.
            </li>
            <li>
              Rights related to automated decision-making, including profiling: users may request that we provide a copy
              of the automated processing activities we conduct if they believe that data is being unlawfully processed.
            </li>
          </ul>
          <p className="mb-8">
            Users or holders of personal data provided through the platform may exercise these rights over their
            personal data at any time and without limitation by sending their request through our contact information or
            contact form. The request to exercise their rights will be attended and answered within a maximum period of
            10 working days.
          </p>

          <h2 className="mb-8 text-4xl font-semibold">11. CHILDREN’S ONLINE PRIVACY PROTECTION</h2>
          <p className="mb-8">
            We comply with the requirements of national and international data protection regulations regarding the
            protection of personal data of minors. Our platform is intended only for users over the age of 18, therefore
            we do not collect any information from children under the age of 18. If we become aware that a child under
            the age of 18 has provided us with personal information, we will take steps to delete such information.
          </p>

          <h2 className="mb-8 text-4xl font-semibold">12. THIRD PARTIES</h2>
          <p className="mb-8">
            Except as otherwise expressly included in this privacy policy, this document addresses only the use and
            disclosure of information that QuikFixs collects from you. If you disclose your information to third
            parties, whether other users or third parties, different rules may apply to their use or disclosure of the
            information you disclose to them. QuikFixs does not control the privacy policies of third parties, and you
            are subject to the privacy policies of those third parties where applicable. QuikFixs is not responsible for
            the privacy or security practices of other websites, platforms or services, including those linked from our
            platform. Please review the privacy policies of any third-party websites, platforms or services you access
            through the QuikFixs platform.
          </p>

          <h2 className="mb-8 text-4xl font-semibold">13. CHANGES TO PRIVACY POLICY</h2>
          <p className="mb-8">
            We reserve the right to change our privacy policy at any time. Changes will be promptly notified to our
            users through any electronic means and posted on the platform. Your continued use of our platform following
            such changes will signify your acceptance of the changes.
          </p>

          <h2 className="mb-8 text-4xl font-semibold">14. CONTACT US</h2>
          <p className="mb-8">
            If you have questions or concerns about these privacy policy and the handling and security of your data,
            please contact us through our contact information below:
          </p>
          <p className="mb-8 font-semibold">QUIKFIXS SERVICES INC.</p>
          <p className="mb-8 font-semibold">Email: support@quikfixs.com</p>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
